spring.application.name=memoria
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG